#!/bin/bash
set -e

# Build script for Kross (Server, CLI, and Obfuscated Client Example)

echo "Building Server..."
go build -o dist/kross-server ./cmd/kross-server

echo "Building CLI..."
go build -o dist/kross-cli ./cmd/kross-cli

# Check if garble is installed for obfuscation
if ! command -v garble &> /dev/null
then
    echo "Garble not found. Installing..."
    go install mvdan.cc/garble@latest
    export PATH=$PATH:$(go env GOPATH)/bin
fi

echo "Building Obfuscated Client Example..."
# We will create a dummy client main.go to demonstrate obfuscated build
cat << 'EOF' > cmd/client-example.go
package main

import (
	"crypto/ed25519"
	"fmt"
	"os"

	"github.com/user/kross/pkg/client"
	"github.com/user/kross/gui"
)

// In a real application, you would embed the actual public key generated by kross-cli keygen.
var embeddedPublicKey = []byte{/* Replace with your public key bytes */}

func main() {
	if len(embeddedPublicKey) == 0 {
		fmt.Println("This is an example client. Replace embeddedPublicKey with your actual key.")
		// Using a dummy key just for compilation
		embeddedPublicKey = make([]byte, ed25519.PublicKeySize)
	}

	c, err := client.New(client.Config{
		PublicKey: embeddedPublicKey,
		ServerURL: "http://localhost:8080", // Replace with actual server URL
		AppName:   "KrossExample",
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to init client: %v\n", err)
		os.Exit(1)
	}

	if err := c.CheckLicense(); err != nil {
		fmt.Println("License verification failed:", err)
		if !gui.ShowActivationWindow(c, "Kross Example") {
			fmt.Println("Activation cancelled. Exiting.")
			os.Exit(1)
		}
	}

	fmt.Println("License is valid! Starting application...")
	// Start your main application logic here
}
EOF

# Build using garble for obfuscation
garble -literals -tiny -seed=random build -ldflags="-s -w" -trimpath -o dist/client-example ./cmd/client-example.go

echo "Build complete! Binaries are in the dist/ folder."
